"""
Django settings for quanlynet project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r-#%nx%en@rh7yyln*rvf&s2rq5@0bac8^+@_x)p9k^g-3n=)^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# quanlynet/settings.py

INSTALLED_APPS = [
    # 1. App giao diện admin (phải nằm trên cùng)
    'jazzmin',
    'dashboard',
    'channels',
    # 2. Các app mặc định của Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes', # App gây ra lỗi
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', 
    
    # 3. Các app của bên thứ ba khác (nếu có)
    
    # 4. Các app của chính bạn (nằm ở cuối cùng)
    'accounts.apps.AccountsConfig',
    'quanly.apps.QuanlyConfig',
    
    
]
# <<< CẤU HÌNH ASGI VÀ CHANNELS >>>
ASGI_APPLICATION = 'quanlynet.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.pubsub.RedisPubSubChannelLayer', 
        'CONFIG': {
            "hosts": [('127.0.0.1', 6380)], # Đảm bảo Redis đang chạy trên cổng 6379
        },
    },
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'quanlynet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'quanlynet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'quanlynet_db',  # Tên database mới bạn sẽ tạo
        'USER': 'root',           # User MySQL của bạn
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.TaiKhoan'
# quanlynet/settings.py

# ... (các settings khác) ...

# TÙY CHỈNH GIAO DIỆN JAZZMIN
JAZZMIN_SETTINGS = {
    "site_title": "Quản Lý Quán Net",
    "site_header": "Quản Net Pro",
    "site_brand": "Quản Net Pro",
    "site_logo": None,  # Bạn có thể đặt đường dẫn tới file logo ở đây
    "welcome_sign": "Chào mừng đến với trang quản trị Quản Net Pro",
    "copyright": "Quản Net Pro Ltd",
}
# settings.py

# ... các cài đặt khác của bạn

# URL để chuyển hướng người dùng đến khi họ chưa đăng nhập
LOGIN_URL = '/accounts/login/'

# URL để chuyển hướng người dùng đến sau khi họ đăng nhập thành công
LOGIN_REDIRECT_URL = '/pos/' # Chuyển đến trang POS sau khi login

# URL để chuyển hướng người dùng đến sau khi họ đăng xuất
LOGOUT_REDIRECT_URL = '/accounts/login/' # Quay về trang login sau khi logout