# Generated by Django 5.2.5 on 2025-09-03 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='DonHangDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('trang_thai_thanh_toan', models.CharField(choices=[('CHUA_THANH_TOAN', 'Chưa thanh toán (cộng vào hóa đơn cuối)'), ('DA_THANH_TOAN_NGAY', 'Đã thanh toán ngay')], default='CHUA_THANH_TOAN', max_length=20)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('CHUA_THANH_TOAN', 'Chưa thanh toán'), ('DA_THANH_TOAN', 'Đã thanh toán')], default='CHUA_THANH_TOAN', max_length=20)),
                ('tong_tien_gio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tong_tien_dich_vu', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền dịch vụ (chưa trả)')),
                ('phai_thanh_toan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('tai_khoan', models.OneToOneField(limit_choices_to={'loai_tai_khoan': 'KHACHHANG'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('so_du', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số dư tài khoản')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca', models.CharField(max_length=100, unique=True, verbose_name='Tên loại ca')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu theo quy định')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc theo quy định')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả (tùy chọn)')),
            ],
            options={
                'verbose_name_plural': 'Các Loại Ca',
                'ordering': ['gio_bat_dau'],
            },
        ),
        migrations.CreateModel(
            name='LoaiMay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=50, unique=True, verbose_name='Tên loại máy')),
                ('don_gia_gio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá mỗi giờ (VNĐ/giờ)')),
            ],
        ),
        migrations.CreateModel(
            name='NguyenLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nguyen_lieu', models.CharField(max_length=100, unique=True, verbose_name='Tên nguyên liệu/hàng hóa')),
                ('don_vi_tinh', models.CharField(max_length=20, verbose_name='Đơn vị tính (VD: lon, gói, kg)')),
                ('so_luong_ton', models.FloatField(default=0, verbose_name='Số lượng tồn kho (hệ thống tính)')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('tai_khoan', models.OneToOneField(limit_choices_to={'loai_tai_khoan': 'NHANVIEN'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('chuc_vu', models.CharField(default='Nhân viên', max_length=100, verbose_name='Chức vụ')),
            ],
        ),
        migrations.CreateModel(
            name='May',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_may', models.CharField(max_length=50, unique=True, verbose_name='Tên máy')),
                ('trang_thai', models.CharField(choices=[('TRONG', 'Trống'), ('DANG_SU_DUNG', 'Đang sử dụng'), ('HONG', 'Hỏng')], default='TRONG', max_length=20, verbose_name='Trạng thái')),
                ('loai_may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.loaimay', verbose_name='Loại máy')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=100, unique=True, verbose_name='Tên món')),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá bán')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng?')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.danhmucmenu', verbose_name='Danh mục')),
                ('nguyen_lieu_tuong_ung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.nguyenlieu', verbose_name='Hàng hóa trong kho (nếu có)')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('don_gia_luc_dat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quanly.donhangdichvu')),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='GiaoDichTaiChinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_giao_dich', models.CharField(choices=[('NAP_TIEN', 'Nạp tiền vào tài khoản'), ('PAY_INVOICE', 'Thanh toán hóa đơn (tiền mặt/ck)'), ('PAY_ORDER', 'Thanh toán order lẻ (tiền mặt/ck)'), ('USE_BALANCE', 'Sử dụng tài khoản (trừ tiền giờ)')], max_length=20)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('thoi_gian_giao_dich', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_le_lien_quan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.donhangdichvu')),
                ('hoa_don_lien_quan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.hoadon')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khachhang')),
                ('nhan_vien_thuc_hien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='PhienSuDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_thuc', models.CharField(choices=[('TRA_SAU', 'Trả sau (khách vãng lai)'), ('TRA_TRUOC', 'Trả trước (tài khoản thành viên)')], default='TRA_SAU', max_length=10)),
                ('thoi_gian_bat_dau', models.DateTimeField(default=django.utils.timezone.now)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('DANG_DIEN_RA', 'Đang diễn ra'), ('DA_KET_THUC', 'Đã kết thúc')], default='DANG_DIEN_RA', max_length=20)),
                ('hoa_don', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phien_su_dung', to='quanly.hoadon')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khachhang')),
                ('may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.may')),
                ('nhan_vien_mo_phien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien')),
            ],
        ),
        migrations.AddField(
            model_name='donhangdichvu',
            name='phien_su_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_don_hang', to='quanly.phiensudung'),
        ),
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhap', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien', verbose_name='Người nhập kho')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.FloatField(verbose_name='Số lượng nhập')),
                ('don_gia_nhap', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Đơn giá nhập')),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nguyenlieu', verbose_name='Nguyên liệu')),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quanly.phieunhapkho')),
            ],
        ),
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau_thuc_te', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bắt đầu thực tế')),
                ('thoi_gian_ket_thuc_thuc_te', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc thực tế')),
                ('tien_mat_ban_dau', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền mặt ban đầu trong két')),
                ('tien_mat_cuoi_ca', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tiền mặt cuối ca')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('trang_thai', models.CharField(choices=[('DANG_LAM', 'Đang làm việc'), ('DA_KET_THUC', 'Đã kết thúc')], default='DANG_LAM', max_length=20, verbose_name='Trạng thái ca')),
                ('loai_ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.loaica', verbose_name='Loại ca')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name_plural': 'Các Ca Làm Việc',
                'ordering': ['-thoi_gian_bat_dau_thuc_te'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('trang_thai', 'DANG_LAM')), fields=('nhan_vien',), name='unique_active_shift_per_employee')],
            },
        ),
    ]
