# Generated by Django 5.2.5 on 2025-09-10 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau_thuc_te', models.DateTimeField()),
                ('thoi_gian_ket_thuc_thuc_te', models.DateTimeField(blank=True, null=True)),
                ('ngay_lam_viec', models.DateField(default=django.utils.timezone.now)),
                ('tien_mat_ban_dau', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trang_thai', models.CharField(choices=[('DANG_DIEN_RA', 'Đang diễn ra'), ('DA_KET_THUC', 'Đã kết thúc')], default='DANG_DIEN_RA', max_length=20)),
                ('tien_mat_cuoi_ca', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền mặt cuối ca (NV nhập)')),
                ('tong_doanh_thu_he_thong', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng doanh thu (hệ thống)')),
                ('chenh_lech', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Chênh lệch')),
            ],
            options={
                'verbose_name_plural': 'Các Ca Làm Việc Thực Tế',
            },
        ),
        migrations.CreateModel(
            name='DanhMucMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('so_du', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số dư')),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khuyen_mai', models.CharField(max_length=50, unique=True)),
                ('mo_ta', models.TextField()),
                ('loai_giam_gia', models.CharField(choices=[('PHAN_TRAM', 'Phần trăm'), ('SO_TIEN', 'Số tiền cố định')], max_length=20)),
                ('gia_tri', models.FloatField()),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca', models.CharField(max_length=100, unique=True, verbose_name='Tên ca')),
                ('gio_bat_dau', models.TimeField(verbose_name='Giờ bắt đầu dự kiến')),
                ('gio_ket_thuc', models.TimeField(verbose_name='Giờ kết thúc dự kiến')),
            ],
            options={
                'verbose_name_plural': 'Các Loại Ca',
            },
        ),
        migrations.CreateModel(
            name='LoaiMay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=50, unique=True, verbose_name='Tên loại máy')),
                ('don_gia_gio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá/giờ')),
            ],
        ),
        migrations.CreateModel(
            name='NguyenLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nguyen_lieu', models.CharField(max_length=100, unique=True, verbose_name='Tên hàng hóa')),
                ('don_vi_tinh', models.CharField(max_length=20, verbose_name='Đơn vị tính')),
                ('so_luong_ton', models.FloatField(default=0, verbose_name='Số lượng tồn kho')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonHangDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_don_hang', models.CharField(choices=[('GHI_NO', 'Ghi nợ'), ('BAN_LE', 'Bán lẻ')], default='GHI_NO', max_length=10)),
                ('da_thanh_toan', models.BooleanField(default=False)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ca_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_don_hang', to='quanly.calamviec')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('tong_tien_gio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tong_tien_dich_vu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tien_giam_gia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tong_cong', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('da_thanh_toan', models.BooleanField(default=False)),
                ('ca_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_hoa_don', to='quanly.calamviec')),
                ('khuyen_mai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khuyenmai')),
            ],
        ),
        migrations.CreateModel(
            name='GiaoDichTaiChinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_giao_dich', models.CharField(choices=[('NAP_TIEN', 'Nạp tiền'), ('THANH_TOAN_HOA_DON', 'Thanh toán hóa đơn'), ('THANH_TOAN_ORDER_LE', 'Thanh toán order lẻ'), ('TRU_TIEN_GIO', 'Trừ tiền giờ tự động'), ('ADMIN_ADJUST', 'Admin điều chỉnh')], max_length=30)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('thoi_gian_giao_dich', models.DateTimeField(default=django.utils.timezone.now)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
                ('ca_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_giao_dich', to='quanly.calamviec')),
                ('don_hang_le', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giao_dich', to='quanly.donhangdichvu')),
                ('hoa_don', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_giao_dich', to='quanly.hoadon')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khachhang')),
            ],
        ),
        migrations.AddField(
            model_name='calamviec',
            name='loai_ca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quanly.loaica', verbose_name='Loại ca'),
        ),
        migrations.CreateModel(
            name='May',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_may', models.CharField(max_length=50, unique=True, verbose_name='Tên máy')),
                ('trang_thai', models.CharField(choices=[('TRONG', 'Trống'), ('DANG_SU_DUNG', 'Đang sử dụng'), ('HONG', 'Hỏng')], default='TRONG', max_length=20, verbose_name='Trạng thái')),
                ('loai_may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.loaimay', verbose_name='Loại máy')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=100, unique=True, verbose_name='Tên món')),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá bán')),
                ('is_available', models.BooleanField(default=True, verbose_name='Có sẵn?')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.danhmucmenu', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='DinhLuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_can', models.FloatField(verbose_name='Số lượng cần')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinh_luong', to='quanly.menuitem')),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nguyenlieu')),
            ],
            options={
                'unique_together': {('menu_item', 'nguyen_lieu')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quanly.donhangdichvu')),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='nguyen_lieu_thanh_phan',
            field=models.ManyToManyField(related_name='menu_items', through='quanly.DinhLuong', to='quanly.nguyenlieu'),
        ),
        migrations.CreateModel(
            name='LichSuThayDoiKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_thay_doi', models.FloatField(help_text='Số dương cho Nhập kho, số âm cho Hủy hàng.')),
                ('loai_thay_doi', models.CharField(choices=[('NHAP_KHO', 'Nhập kho từ nhà cung cấp'), ('HUY_HANG', 'Báo hỏng / Hủy hàng'), ('DIEU_CHINH', 'Admin điều chỉnh thủ công')], max_length=20)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('ly_do', models.CharField(max_length=255)),
                ('ca_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_thay_doi_kho', to='quanly.calamviec')),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nguyenlieu')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien')),
            ],
            options={
                'verbose_name_plural': 'Lịch Sử Thay Đổi Kho',
            },
        ),
        migrations.AddField(
            model_name='calamviec',
            name='nhan_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_ca_lam_viec', to='quanly.nhanvien'),
        ),
        migrations.CreateModel(
            name='PhienSuDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_thuc', models.CharField(choices=[('TRA_SAU', 'Trả sau'), ('TRA_TRUOC', 'Trả trước')], max_length=10)),
                ('thoi_gian_bat_dau', models.DateTimeField(default=django.utils.timezone.now)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('DANG_DIEN_RA', 'Đang diễn ra'), ('DA_KET_THUC', 'Đã kết thúc'), ('DA_HUY', 'Đã hủy')], default='DANG_DIEN_RA', max_length=20)),
                ('ca_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_phien_su_dung', to='quanly.calamviec')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khachhang')),
                ('may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_phien_su_dung', to='quanly.may')),
                ('nhan_vien_mo_phien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_phien_da_mo', to='quanly.nhanvien')),
            ],
        ),
        migrations.AddField(
            model_name='hoadon',
            name='phien_su_dung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hoa_don', to='quanly.phiensudung'),
        ),
        migrations.AddField(
            model_name='donhangdichvu',
            name='phien_su_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cac_don_hang', to='quanly.phiensudung'),
        ),
        migrations.CreateModel(
            name='PhieuKiemKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('da_xac_nhan', models.BooleanField(default=False, help_text='Đánh dấu khi nhân viên đã chốt số liệu cuối cùng.')),
                ('ca_lam_viec', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_kiem_ke', to='quanly.calamviec')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_phieu_kiem_ke', to='quanly.nhanvien')),
            ],
            options={
                'verbose_name_plural': 'Các Phiếu Kiểm Kê',
            },
        ),
        migrations.CreateModel(
            name='ChiTietKiemKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ton_he_thong', models.FloatField(help_text='Số lượng hệ thống ghi nhận tại thời điểm kiểm kê.', verbose_name='Tồn hệ thống')),
                ('ton_thuc_te', models.FloatField(help_text='Số lượng nhân viên đếm được.', verbose_name='Tồn thực tế')),
                ('chenh_lech', models.FloatField(verbose_name='Chênh lệch')),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nguyenlieu')),
                ('phieu_kiem_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quanly.phieukiemke')),
            ],
            options={
                'unique_together': {('phieu_kiem_ke', 'nguyen_lieu')},
            },
        ),
    ]
