# Generated by Django 5.2.5 on 2025-08-20 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('tai_khoan', models.OneToOneField(limit_choices_to={'loai_tai_khoan': 'KHACHHANG'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Số điện thoại')),
                ('diem_tich_luy', models.PositiveIntegerField(default=0, verbose_name='Điểm tích lũy')),
                ('so_du', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số dư tài khoản')),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khuyen_mai', models.CharField(max_length=50, unique=True, verbose_name='Mã khuyến mãi')),
                ('mo_ta', models.TextField(verbose_name='Mô tả')),
                ('loai_giam_gia', models.CharField(choices=[('PHAN_TRAM', 'Phần trăm'), ('SO_TIEN', 'Số tiền cố định')], max_length=20)),
                ('gia_tri', models.FloatField(verbose_name='Giá trị (VD: 20 cho 20%, 20000 cho 20,000 VND)')),
                ('ngay_bat_dau', models.DateTimeField()),
                ('ngay_ket_thuc', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động?')),
            ],
        ),
        migrations.CreateModel(
            name='LoaiMay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=50, unique=True, verbose_name='Tên loại máy')),
                ('don_gia_gio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá mỗi giờ')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=100, unique=True, verbose_name='Tên món')),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng?')),
            ],
        ),
        migrations.CreateModel(
            name='NguyenLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nguyen_lieu', models.CharField(max_length=100, unique=True, verbose_name='Tên nguyên liệu')),
                ('don_vi_tinh', models.CharField(max_length=20, verbose_name='Đơn vị tính (VD: lon, chai, kg)')),
                ('so_luong_ton', models.FloatField(default=0, verbose_name='Số lượng tồn kho')),
                ('nguong_canh_bao', models.FloatField(default=10, verbose_name='Ngưỡng cảnh báo hết hàng')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('tai_khoan', models.OneToOneField(limit_choices_to={'loai_tai_khoan': 'NHANVIEN'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
                ('chuc_vu', models.CharField(default='Nhân viên', max_length=100, verbose_name='Chức vụ')),
                ('ngay_vao_lam', models.DateField(auto_now_add=True, verbose_name='Ngày vào làm')),
            ],
        ),
        migrations.CreateModel(
            name='May',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_may', models.CharField(max_length=50, unique=True, verbose_name='Tên máy')),
                ('trang_thai', models.CharField(choices=[('TRONG', 'Trống'), ('DANG_SU_DUNG', 'Đang sử dụng'), ('BAO_TRI', 'Bảo trì')], default='TRONG', max_length=20, verbose_name='Trạng thái')),
                ('loai_may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.loaimay', verbose_name='Loại máy')),
            ],
        ),
        migrations.CreateModel(
            name='GiaoDich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu')),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('tong_tien_gio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tong_tien_dich_vu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('giam_gia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('thanh_tien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trang_thai', models.CharField(choices=[('DANG_DIEN_RA', 'Đang diễn ra'), ('DA_THANH_TOAN', 'Đã thanh toán'), ('DA_HUY', 'Đã hủy')], default='DANG_DIEN_RA', max_length=20)),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khachhang', verbose_name='Khách hàng thành viên')),
                ('may', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giao_dich_hien_tai', to='quanly.may', verbose_name='Máy đang sử dụng')),
                ('nhan_vien_mo_phien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.nhanvien', verbose_name='Nhân viên mở phiên')),
            ],
        ),
        migrations.CreateModel(
            name='DinhLuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_can', models.FloatField(verbose_name='Số lượng cần cho 1 đơn vị món')),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.menu', verbose_name='Món')),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanly.nguyenlieu', verbose_name='Nguyên liệu')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietGiaoDich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('don_gia_luc_dat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá lúc đặt')),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Thành tiền')),
                ('giao_dich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_items', to='quanly.giaodich', verbose_name='Giao dịch')),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.menu', verbose_name='Món')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='nguyen_lieu',
            field=models.ManyToManyField(through='quanly.DinhLuong', to='quanly.nguyenlieu', verbose_name='Nguyên liệu cấu thành'),
        ),
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu ca')),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc ca')),
                ('doanh_thu_ca', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Doanh thu trong ca')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien', verbose_name='Nhân viên')),
            ],
        ),
    ]
