# Generated by Django 5.2.5 on 2025-10-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsuthaydoikho',
            name='nhan_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien'),
        ),
    ]
