# Generated by Django 5.2.5 on 2025-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calamviec',
            name='chenh_lech',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Chênh lệch tiền mặt'),
        ),
        migrations.AddField(
            model_name='calamviec',
            name='tien_mat_cuoi_ca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tiền mặt NV nộp cuối ca'),
        ),
        migrations.AddField(
            model_name='calamviec',
            name='tong_doanh_thu_he_thong',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tổng doanh thu trên hệ thống'),
        ),
    ]
