# Generated by Django 5.2.5 on 2025-08-21 04:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giaodich',
            name='khach_hang',
        ),
        migrations.RemoveField(
            model_name='giaodich',
            name='may',
        ),
        migrations.RemoveField(
            model_name='giaodich',
            name='nhan_vien_mo_phien',
        ),
        migrations.RemoveField(
            model_name='calamviec',
            name='doanh_thu_ca',
        ),
        migrations.AddField(
            model_name='calamviec',
            name='doanh_thu_ca_ban_dau',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tiền mặt đầu ca'),
        ),
        migrations.AddField(
            model_name='calamviec',
            name='doanh_thu_ca_cuoi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Doanh thu tổng trong ca'),
        ),
        migrations.AlterField(
            model_name='calamviec',
            name='thoi_gian_bat_dau',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bắt đầu ca'),
        ),
        migrations.CreateModel(
            name='DonHangDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('CHO_XU_LY', 'Chờ xử lý'), ('DANG_THUC_HIEN', 'Đang thực hiện'), ('DA_GIAO', 'Đã giao')], default='CHO_XU_LY', max_length=20)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nhan_vien_tao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.PositiveIntegerField(default=1)),
                ('don_gia_luc_dat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.menu')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quanly.donhangdichvu')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai', models.CharField(choices=[('CHUA_THANH_TOAN', 'Chưa thanh toán'), ('DA_THANH_TOAN', 'Đã thanh toán'), ('DA_HUY', 'Đã hủy')], default='CHUA_THANH_TOAN', max_length=20)),
                ('tong_tien_gio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tong_tien_dich_vu', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tien_giam_gia', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số tiền được giảm')),
                ('phai_thanh_toan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
                ('thoi_gian_thanh_toan', models.DateTimeField(blank=True, null=True)),
                ('khuyen_mai_ap_dung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khuyenmai', verbose_name='Khuyến mãi')),
            ],
        ),
        migrations.CreateModel(
            name='GiaoDichTaiChinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_giao_dich', models.CharField(choices=[('NAP_TIEN', 'Nạp tiền vào tài khoản'), ('PAY_CASH', 'Thanh toán tiền mặt'), ('PAY_BANK', 'Thanh toán chuyển khoản'), ('PAY_ACC', 'Thanh toán bằng tài khoản'), ('REFUND', 'Hoàn tiền')], max_length=20)),
                ('so_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('thoi_gian_giao_dich', models.DateTimeField(default=django.utils.timezone.now)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khachhang')),
                ('nhan_vien_thuc_hien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien')),
                ('hoa_don_lien_quan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.hoadon')),
            ],
        ),
        migrations.CreateModel(
            name='PhienSuDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau', models.DateTimeField(default=django.utils.timezone.now)),
                ('thoi_gian_ket_thuc', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('DANG_DIEN_RA', 'Đang diễn ra'), ('DA_KET_THUC', 'Đã kết thúc')], default='DANG_DIEN_RA', max_length=20)),
                ('hoa_don', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phien_su_dung', to='quanly.hoadon')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khachhang')),
                ('may', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_phien_su_dung', to='quanly.may')),
                ('nhan_vien_mo_phien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phien_da_mo', to='quanly.nhanvien')),
            ],
        ),
        migrations.AddField(
            model_name='donhangdichvu',
            name='phien_su_dung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_don_hang', to='quanly.phiensudung'),
        ),
        migrations.DeleteModel(
            name='ChiTietGiaoDich',
        ),
        migrations.DeleteModel(
            name='GiaoDich',
        ),
    ]
