# Generated by Django 5.2.5 on 2025-09-12 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_alter_khachhang_tai_khoan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaimay',
            name='don_gia_gio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loaimay',
            name='ten_loai',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='loai_may',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.loaimay'),
        ),
        migrations.AlterField(
            model_name='may',
            name='ten_may',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='may',
            name='trang_thai',
            field=models.CharField(choices=[('TRONG', 'Trống'), ('DANG_SU_DUNG', 'Đang sử dụng'), ('HONG', 'Hỏng')], default='TRONG', max_length=20),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='tai_khoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nhanvien', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
