# Generated by Django 5.2.5 on 2025-08-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_calamviec_chenh_lech_calamviec_tien_mat_cuoi_ca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calamviec',
            name='chenh_lech',
        ),
        migrations.RemoveField(
            model_name='calamviec',
            name='tien_mat_cuoi_ca',
        ),
        migrations.RemoveField(
            model_name='calamviec',
            name='tong_doanh_thu_he_thong',
        ),
    ]
