# Generated by Django 5.2.5 on 2025-08-21 04:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_remove_giaodich_khach_hang_remove_giaodich_may_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
            ],
        ),
        migrations.RemoveField(
            model_name='dinhluong',
            name='mon',
        ),
        migrations.RemoveField(
            model_name='dinhluong',
            name='nguyen_lieu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='nguyen_lieu',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='khuyen_mai_ap_dung',
        ),
        migrations.RemoveField(
            model_name='donhangdichvu',
            name='nhan_vien_tao',
        ),
        migrations.RemoveField(
            model_name='donhangdichvu',
            name='trang_thai',
        ),
        migrations.RemoveField(
            model_name='giaodichtaichinh',
            name='ghi_chu',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='thoi_gian_thanh_toan',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='tien_giam_gia',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='diem_tich_luy',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='so_dien_thoai',
        ),
        migrations.RemoveField(
            model_name='nguyenlieu',
            name='nguong_canh_bao',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='ngay_vao_lam',
        ),
        migrations.AddField(
            model_name='donhangdichvu',
            name='trang_thai_thanh_toan',
            field=models.CharField(choices=[('CHUA_THANH_TOAN', 'Chưa thanh toán (cộng vào hóa đơn cuối)'), ('DA_THANH_TOAN_NGAY', 'Đã thanh toán ngay')], default='CHUA_THANH_TOAN', max_length=20),
        ),
        migrations.AddField(
            model_name='giaodichtaichinh',
            name='order_le_lien_quan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.donhangdichvu'),
        ),
        migrations.AddField(
            model_name='phiensudung',
            name='hinh_thuc',
            field=models.CharField(choices=[('TRA_SAU', 'Trả sau (khách vãng lai)'), ('TRA_TRUOC', 'Trả trước (tài khoản thành viên)')], default='TRA_SAU', max_length=10),
        ),
        migrations.AlterField(
            model_name='giaodichtaichinh',
            name='loai_giao_dich',
            field=models.CharField(choices=[('NAP_TIEN', 'Nạp tiền vào tài khoản'), ('PAY_INVOICE', 'Thanh toán hóa đơn (tiền mặt/ck)'), ('PAY_ORDER', 'Thanh toán order lẻ (tiền mặt/ck)'), ('USE_BALANCE', 'Sử dụng tài khoản (trừ tiền giờ)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='tong_tien_dich_vu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền dịch vụ (chưa trả)'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='trang_thai',
            field=models.CharField(choices=[('CHUA_THANH_TOAN', 'Chưa thanh toán'), ('DA_THANH_TOAN', 'Đã thanh toán')], default='CHUA_THANH_TOAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='tai_khoan',
            field=models.OneToOneField(limit_choices_to={'loai_tai_khoan': 'KHACHHANG'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loaimay',
            name='don_gia_gio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá mỗi giờ (VNĐ/giờ)'),
        ),
        migrations.AlterField(
            model_name='may',
            name='trang_thai',
            field=models.CharField(choices=[('TRONG', 'Trống'), ('DANG_SU_DUNG', 'Đang sử dụng'), ('HONG', 'Hỏng')], default='TRONG', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='nguyenlieu',
            name='don_vi_tinh',
            field=models.CharField(max_length=20, verbose_name='Đơn vị tính (VD: lon, gói, kg)'),
        ),
        migrations.AlterField(
            model_name='nguyenlieu',
            name='so_luong_ton',
            field=models.FloatField(default=0, verbose_name='Số lượng tồn kho (hệ thống tính)'),
        ),
        migrations.AlterField(
            model_name='nguyenlieu',
            name='ten_nguyen_lieu',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên nguyên liệu/hàng hóa'),
        ),
        migrations.AlterField(
            model_name='nhanvien',
            name='tai_khoan',
            field=models.OneToOneField(limit_choices_to={'loai_tai_khoan': 'NHANVIEN'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phiensudung',
            name='hoa_don',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phien_su_dung', to='quanly.hoadon'),
        ),
        migrations.AlterField(
            model_name='phiensudung',
            name='may',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.may'),
        ),
        migrations.AlterField(
            model_name='phiensudung',
            name='nhan_vien_mo_phien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=100, unique=True, verbose_name='Tên món')),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Đơn giá bán')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng?')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.danhmucmenu', verbose_name='Danh mục')),
                ('nguyen_lieu_tuong_ung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.nguyenlieu', verbose_name='Hàng hóa trong kho (nếu có)')),
            ],
        ),
        migrations.AlterField(
            model_name='chitietdonhang',
            name='mon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.menuitem'),
        ),
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nhap', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập')),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_nhap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien', verbose_name='Người nhập kho')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.FloatField(verbose_name='Số lượng nhập')),
                ('don_gia_nhap', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Đơn giá nhập')),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nguyenlieu', verbose_name='Nguyên liệu')),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='quanly.phieunhapkho')),
            ],
        ),
        migrations.DeleteModel(
            name='CaLamViec',
        ),
        migrations.DeleteModel(
            name='DinhLuong',
        ),
        migrations.DeleteModel(
            name='KhuyenMai',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
