# Generated by Django 5.2.5 on 2025-10-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0002_alter_lichsuthaydoikho_nhan_vien'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhangdichvu',
            name='khuyen_mai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khuyenmai', verbose_name='Mã khuyến mãi áp dụng'),
        ),
        migrations.AddField(
            model_name='donhangdichvu',
            name='tien_giam_gia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Số tiền giảm giá'),
        ),
    ]
