# Generated by Django 5.2.5 on 2025-09-12 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_alter_loaimay_don_gia_gio_alter_loaimay_ten_loai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giaodichtaichinh',
            options={'ordering': ['-thoi_gian_giao_dich'], 'verbose_name': 'Giao dịch tài chính', 'verbose_name_plural': 'Sổ Cái Giao Dịch Tài Chính'},
        ),
        migrations.AlterField(
            model_name='giaodichtaichinh',
            name='ca_lam_viec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cac_giao_dich', to='quanly.calamviec', verbose_name='Ca làm việc'),
        ),
        migrations.AlterField(
            model_name='giaodichtaichinh',
            name='don_hang_le',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giao_dich', to='quanly.donhangdichvu', verbose_name='Đơn hàng lẻ'),
        ),
        migrations.AlterField(
            model_name='giaodichtaichinh',
            name='ghi_chu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='giaodichtaichinh',
            name='hoa_don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_giao_dich', to='quanly.hoadon', verbose_name='Hóa đơn'),
        ),
        migrations.AlterField(
            model_name='giaodichtaichinh',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quanly.khachhang', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='giaodichtaichinh',
            name='loai_giao_dich',
            field=models.CharField(choices=[('NAP_TIEN', 'Nạp tiền vào tài khoản thành viên'), ('THANH_TOAN_HOA_DON', 'Thanh toán hóa đơn (Tiền mặt/Chuyển khoản)'), ('THANH_TOAN_ORDER_LE', 'Thanh toán order lẻ (Tiền mặt/Chuyển khoản)'), ('THANH_TOAN_TK', 'Thanh toán hóa đơn (Trừ vào tài khoản)'), ('ADMIN_ADJUST', 'Admin điều chỉnh')], max_length=30, verbose_name='Loại giao dịch'),
        ),
        migrations.AlterField(
            model_name='giaodichtaichinh',
            name='so_tien',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền'),
        ),
        migrations.AlterField(
            model_name='giaodichtaichinh',
            name='thoi_gian_giao_dich',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian giao dịch'),
        ),
    ]
