# Generated by Django 5.2.5 on 2025-09-03 09:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_danhmucmenu_remove_dinhluong_mon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiCa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ca', models.CharField(max_length=100, unique=True, verbose_name='Tên loại ca')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name_plural': 'Các Loại Ca',
                'ordering': ['ten_ca'],
            },
        ),
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_bat_dau_thuc_te', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bắt đầu thực tế')),
                ('thoi_gian_ket_thuc_thuc_te', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc thực tế')),
                ('tien_mat_ban_dau', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tiền mặt ban đầu trong két')),
                ('tien_mat_cuoi_ca', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tiền mặt cuối ca')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('trang_thai', models.CharField(choices=[('DANG_LAM', 'Đang làm việc'), ('DA_KET_THUC', 'Đã kết thúc')], default='DANG_LAM', max_length=20, verbose_name='Trạng thái ca')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.nhanvien', verbose_name='Nhân viên')),
                ('loai_ca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quanly.loaica', verbose_name='Loại ca')),
            ],
            options={
                'verbose_name_plural': 'Các Ca Làm Việc',
                'ordering': ['-thoi_gian_bat_dau_thuc_te'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('trang_thai', 'DANG_LAM')), fields=('nhan_vien',), name='unique_active_shift_per_employee')],
            },
        ),
    ]
