# Generated by Django 5.2.5 on 2025-10-15 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0003_donhangdichvu_khuyen_mai_donhangdichvu_tien_giam_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='luot_su_dung_toi_da_moi_khach',
            field=models.PositiveIntegerField(default=0, help_text='Số lần tối đa mỗi khách hàng có thể sử dụng khuyến mãi này (0 = không giới hạn).', verbose_name='Số lượt dùng/khách'),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='loai_giam_gia',
            field=models.CharField(choices=[('PHAN_TRAM', 'Phần trăm'), ('SO_TIEN', 'Số tiền cố định'), ('BONUS_NAP_TIEN', 'Bonus nạp tiền vào tài khoản')], max_length=20),
        ),
        migrations.CreateModel(
            name='KhuyenMaiSuDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_su_dung', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khuyen_mai_da_dung', to='quanly.khachhang')),
                ('khuyen_mai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luot_su_dung', to='quanly.khuyenmai')),
            ],
            options={
                'verbose_name': 'Lịch sử sử dụng khuyến mãi',
                'verbose_name_plural': 'Lịch sử sử dụng khuyến mãi',
                'unique_together': {('khuyen_mai', 'khach_hang')},
            },
        ),
    ]
