# Generated by Django 5.2.5 on 2025-10-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0004_khuyenmai_luot_su_dung_toi_da_moi_khach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='loai_bonus_nap_tien',
            field=models.CharField(blank=True, choices=[('PHAN_TRAM_BONUS', 'Phần trăm bonus'), ('SO_TIEN_BONUS', 'Số tiền bonus cố định')], max_length=20, null=True, verbose_name='Loại bonus nạp tiền'),
        ),
    ]
