# Generated by Django 5.2.5 on 2025-09-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0004_loaica_calamviec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaica',
            options={'ordering': ['gio_bat_dau'], 'verbose_name_plural': 'Các Loại Ca'},
        ),
        migrations.AddField(
            model_name='loaica',
            name='gio_bat_dau',
            field=models.TimeField(default='08:00:00', verbose_name='Giờ bắt đầu theo quy định'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loaica',
            name='gio_ket_thuc',
            field=models.TimeField(default='08:00:00', verbose_name='Giờ kết thúc theo quy định'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loaica',
            name='mo_ta',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả (tùy chọn)'),
        ),
    ]
