# Generated by Django 5.2.5 on 2025-09-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0004_alter_giaodichtaichinh_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietkiemke',
            name='chenh_lech',
            field=models.FloatField(default=0, verbose_name='Chênh lệch'),
        ),
        migrations.AlterField(
            model_name='lichsuthaydoikho',
            name='ca_lam_viec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cac_thay_doi_kho', to='quanly.calamviec'),
        ),
    ]
