# Generated by Django 5.2.5 on 2025-09-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0005_alter_chitietkiemke_chenh_lech_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguyenlieu',
            name='gia_von',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá vốn / Đơn vị'),
        ),
    ]
