# Generated by Django 5.2.5 on 2025-10-30 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0005_khuyenmai_loai_bonus_nap_tien'),
    ]

    operations = [
        migrations.AddField(
            model_name='phiensudung',
            name='thoi_gian_kiem_tra_lan_cuoi',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian kiểm tra số dư lần cuối'),
        ),
    ]
