# Generated by Django 5.2.5 on 2025-09-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quanly', '0006_nguyenlieu_gia_von'),
    ]

    operations = [
        migrations.AddField(
            model_name='khuyenmai',
            name='chu_ky_lap_lai',
            field=models.CharField(choices=[('MOT_LAN', 'Áp dụng một lần (theo ngày bắt đầu/kết thúc)'), ('HANG_NGAY', 'Lặp lại Hằng ngày'), ('HANG_TUAN', 'Lặp lại Hàng tuần'), ('HANG_THANG', 'Lặp lại Hàng tháng')], default='MOT_LAN', max_length=20, verbose_name='Chu kỳ lặp lại'),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='ngay_trong_tuan',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Các ngày trong tuần'),
        ),
    ]
